using System.IO.Compression;
using System.Text.Json.Serialization;
using System.Threading.RateLimiting;
using FamilySplit.Api.Endpoints;
using FamilySplit.Api.Hubs;
using FamilySplit.Api.Middleware;
using FamilySplit.Application;
using FamilySplit.Common;
using FamilySplit.Common.Modules;
using FamilySplit.Common.Notifications;
using FamilySplit.Features.Activities;
using FamilySplit.Features.Admin;
using FamilySplit.Features.Auth;
using FamilySplit.Features.Dashboard;
using FamilySplit.Features.Expenses;
using FamilySplit.Features.Families;
using FamilySplit.Features.Groups;
using FamilySplit.Features.Settlements;
using FamilySplit.Features.Users;
using FamilySplit.Infrastructure;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.ResponseCompression;
using Scalar.AspNetCore;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Validate that all registered services can be constructed at startup, catching
// missing registrations and captive-dependency bugs before the first request.
// ValidateScopes catches scoped services accidentally consumed from singletons.
builder.Host.UseDefaultServiceProvider(options =>
{
    options.ValidateOnBuild = true;
    options.ValidateScopes = true;
});

// Remove the default "Server: Kestrel" response header to avoid advertising
// the server technology to potential attackers.
builder.WebHost.ConfigureKestrel(o => o.AddServerHeader = false);

// --- Logging -----------------------------------------------------------------------
// Serilog reads levels from appsettings. Console output format depends on the
// environment: structured JSON in production (parseable by Railway log drains /
// external log services) and human-readable text in development.
var isProduction = builder.Environment.IsProduction();
builder.Host.UseSerilog((ctx, lc) =>
{
    lc.ReadFrom.Configuration(ctx.Configuration)
      .Enrich.FromLogContext();

    if (isProduction)
        lc.WriteTo.Console(new Serilog.Formatting.Json.JsonFormatter());
    else
        lc.WriteTo.Console();
});

// Cache allowed origins once at startup — used by both CORS and the OAuth
// returnUrl allow-list (open-redirect guard in AuthEndpoints).
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
    ?? new[] { "https://localhost:5001", "http://localhost:5000" };

// --- CORS for Blazor WASM client --------------------------------------------------
builder.Services.AddCors(options =>
{
    options.AddPolicy("ClientApp", policy =>
    {
        policy.WithOrigins(allowedOrigins)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// --- Response compression (gzip + brotli for JSON over HTTPS) --------------------
// Trims response payloads by ~70% for typical JSON responses, with a negligible
// CPU cost. EnableForHttps is safe here because the API only accepts JSON
// responses generated by our own code — no static files, no user-controlled
// content that could be vulnerable to BREACH-style attacks.
builder.Services.AddResponseCompression(o =>
{
    o.EnableForHttps = true;
    o.Providers.Add<BrotliCompressionProvider>();
    o.Providers.Add<GzipCompressionProvider>();
    o.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] { "application/problem+json" });
});
builder.Services.Configure<BrotliCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);
builder.Services.Configure<GzipCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);

// --- Rate limiting ----------------------------------------------------------------
// Two-tier protection:
//   • Global per-IP fixed window   — blanket safety net (300 req/min).
//   • Named "auth" sliding window  — tighter per-IP limit on auth endpoints,
//     registered by AuthModule.RegisterServices via its own AddRateLimiter call
//     (options delegates compose — this call keeps the global limiter + OnRejected).
builder.Services.AddRateLimiter(options =>
{
    options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(ctx =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: ctx.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 300,
                Window = TimeSpan.FromMinutes(1),
                QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
                QueueLimit = 0,
            }));

    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;

    options.OnRejected = async (ctx, ct) =>
    {
        ctx.HttpContext.Response.StatusCode = StatusCodes.Status429TooManyRequests;
        ctx.HttpContext.Response.ContentType = "application/json";

        if (ctx.Lease.TryGetMetadata(MetadataName.RetryAfter, out var retryAfter))
        {
            ctx.HttpContext.Response.Headers.RetryAfter =
                ((int)retryAfter.TotalSeconds).ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        await ctx.HttpContext.Response.WriteAsync(
            """{"title":"Too many requests","status":429}""", ct);
    };
});

// --- Common + Application + Infrastructure ----------------------------------------
builder.Services.AddFamilySplitCommon();
builder.Services.AddFamilySplitApplication();
builder.Services.AddFamilySplitInfrastructure(builder.Configuration, builder.Environment);

// Feature modules (populated slice by slice).
IFeatureModule[] modules = [ new ExpensesModule(), new DashboardModule(), new UsersModule(), new GroupsModule(), new ActivitiesModule(), new SettlementsModule(), new AdminModule(), new FamiliesModule(), new AuthModule() ];
foreach (var m in modules) m.RegisterServices(builder.Services, builder.Configuration);

// Serialize enums as strings so API responses are human-readable (e.g. "Open" not 0).
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});

// Require authentication globally. Every endpoint is protected by default;
// public routes (OAuth callbacks, /health) opt out explicitly with .AllowAnonymous().
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

// --- SignalR -----------------------------------------------------------------------
// AddSignalR is part of the ASP.NET Core shared framework — no extra NuGet needed.
// SignalRNotificationService is scoped and registered as INotificationService so
// SettlementService can call it without a direct dependency on SignalR.
builder.Services.AddSignalR();
builder.Services.AddScoped<INotificationService, SignalRNotificationService>();

// Persist Data Protection keys to the application database. The key ring
// encrypts the PKCE state cookie (and any future protected payloads) and must
// survive API restarts and multi-instance deploys.
//   AppDbContext implements IDataProtectionKeyContext (DbSet<DataProtectionKey>).
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>()
    .SetApplicationName("FamilySplit");

// --- OpenAPI / Scalar -------------------------------------------------------------
// Only register the OpenAPI document generator in development — it adds a
// non-trivial chunk to startup time and is never used in production.
if (builder.Environment.IsDevelopment())
{
    builder.Services.AddOpenApi();
}

var app = builder.Build();

// --- Middleware pipeline ----------------------------------------------------------
// Forwarded headers MUST run first. Railway terminates TLS at its edge proxy and
// forwards the request to the container as plain HTTP with X-Forwarded-Proto: https.
// Until this middleware rewrites Request.Scheme and Request.Host, anything that
// reads them sees the raw http scheme — which causes UseHttpsRedirection to fire
// in a loop, builds http:// redirect_uris that Google rejects, and produces Secure
// cookies the browser won't store.
//
// KnownNetworks/KnownProxies are cleared because the proxy IPs Railway uses are
// not stable and we cannot enumerate them. The only safe alternative would be to
// hardcode Railway's egress range, which they don't publish.
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor
                     | ForwardedHeaders.XForwardedProto
                     | ForwardedHeaders.XForwardedHost
};
forwardedHeadersOptions.KnownIPNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);

// Security headers on every response — registered after ForwardedHeaders so any
// header values that depend on scheme (e.g. CSP report-uri) see the correct one.
app.UseMiddleware<SecurityHeadersMiddleware>();

// HSTS + HTTPS redirection are production-only: dev typically runs on a self-signed
// cert and `localhost` is exempt from HSTS preload anyway.
if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseResponseCompression();
app.UseSerilogRequestLogging();
app.UseMiddleware<ValidationExceptionMiddleware>();
app.UseCors("ClientApp");
app.UseRateLimiter();

app.UseAuthentication();
app.UseAuthorization();
// Enriches Serilog log entries with the authenticated caller's UserId and
// UserEmail (from JWT claims) for every subsequent log statement in the request.
app.UseMiddleware<UserLoggingContextMiddleware>();

// --- Health (anonymous) -----------------------------------------------------------
app.MapGet("/health", () => Results.Ok(new
{
    status = "ok",
    service = "FamilySplit.Api",
    utc = DateTimeOffset.UtcNow
})).AllowAnonymous();

// Feature module endpoint mapping.
foreach (var m in modules) m.MapEndpoints(app);

// --- Endpoint groups --------------------------------------------------------------
// Auth: /auth — login/callback/refresh/logout — migrated to AuthModule (vertical slice)
// Users: GET /whoami — migrated to UsersModule (vertical slice)
// Admin: /admin — global-admin family + member CRUD + group management — migrated to AdminModule (vertical slice)
// Families: /families/mine + GET /users/me/profile — migrated to FamiliesModule (vertical slice)
// Groups: /groups — CRUD + join + invite-code + leave — migrated to GroupsModule (vertical slice)
// Activities: /groups/{groupId}/activities — CRUD + participants + close — migrated to ActivitiesModule (vertical slice)
// Expenses: /groups/{groupId}/activities/{activityId}/expenses — migrated to ExpensesModule (vertical slice)
// Settlements: /groups/{groupId}/activities/{activityId}/settlements (+ balances, group/pending lists) — migrated to SettlementsModule (vertical slice)
// Dashboard: /dashboard/stats — migrated to DashboardModule (vertical slice)
app.MapPushEndpoints();           // /push — VAPID subscription management

// SignalR hub — Blazor WASM passes JWT as ?access_token query param because
// WebSocket upgrade requests cannot carry Authorization headers.
app.MapHub<NotificationHub>("/hubs/notifications");


// --- OpenAPI + Scalar UI (dev only) ----------------------------------------------
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi().AllowAnonymous();
    app.MapScalarApiReference().AllowAnonymous();
}

app.Run();

// Exposed for WebApplicationFactory<Program> in integration tests.
public partial class Program { }
