using System.IO.Compression;
using System.Security.Claims;
using System.Text;
using FamilySplit.Api.Auth;
using FamilySplit.Api.Endpoints;
using FamilySplit.Api.Middleware;
using FamilySplit.Application;
using FamilySplit.Infrastructure;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.IdentityModel.Tokens;
using Microsoft.IdentityModel.JsonWebTokens;
using Scalar.AspNetCore;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Remove the default "Server: Kestrel" response header to avoid advertising
// the server technology to potential attackers.
builder.WebHost.ConfigureKestrel(o => o.AddServerHeader = false);

// --- Logging -----------------------------------------------------------------------
// Serilog is configured purely from appsettings to avoid double-write to console
// during startup (the host's default logger is replaced cleanly).
builder.Host.UseSerilog((ctx, lc) => lc
    .ReadFrom.Configuration(ctx.Configuration)
    .Enrich.FromLogContext()
    .WriteTo.Console());

// Cache allowed origins once at startup — used by both CORS and the OAuth
// returnUrl allow-list (open-redirect guard in AuthEndpoints).
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
    ?? new[] { "https://localhost:5001", "http://localhost:5000" };

// --- CORS for Blazor WASM client --------------------------------------------------
builder.Services.AddCors(options =>
{
    options.AddPolicy("ClientApp", policy =>
    {
        policy.WithOrigins(allowedOrigins)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// --- Response compression (gzip + brotli for JSON over HTTPS) --------------------
// Trims response payloads by ~70% for typical JSON responses, with a negligible
// CPU cost. EnableForHttps is safe here because the API only accepts JSON
// responses generated by our own code — no static files, no user-controlled
// content that could be vulnerable to BREACH-style attacks.
builder.Services.AddResponseCompression(o =>
{
    o.EnableForHttps = true;
    o.Providers.Add<BrotliCompressionProvider>();
    o.Providers.Add<GzipCompressionProvider>();
    o.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] { "application/problem+json" });
});
builder.Services.Configure<BrotliCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);
builder.Services.Configure<GzipCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);

// --- HTTP client factory (needed by OAuthHandler for token exchange) -------------
// Named client lets us bound the upstream call so a slow Google response can't
// pin a request thread for minutes on end.
builder.Services.AddHttpClient("google-oauth", c =>
{
    c.Timeout = TimeSpan.FromSeconds(15);
});

// --- Application + Infrastructure -------------------------------------------------
builder.Services.AddFamilySplitApplication();
builder.Services.AddFamilySplitInfrastructure(builder.Configuration, builder.Environment);

// --- Auth: JwtBearer + OAuth handler placeholders ---------------------------------
var jwt = builder.Configuration.GetSection("Jwt");
var signingKey = jwt["SigningKey"]
    ?? throw new InvalidOperationException("Missing config Jwt:SigningKey. Set via user-secrets or env.");
if (Encoding.UTF8.GetByteCount(signingKey) < 32)
    throw new InvalidOperationException("Jwt:SigningKey must be at least 32 bytes (256 bits) for HMAC-SHA256.");
var issuer   = jwt["Issuer"]   ?? "familysplit";
var audience = jwt["Audience"] ?? "familysplit-client";

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        // Use the modern JsonWebTokenHandler — faster than the legacy
        // JwtSecurityTokenHandler and the future-default for JwtBearer.
        options.MapInboundClaims = false;
        options.SaveToken = false;
        options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            RequireExpirationTime = true,
            RequireSignedTokens = true,
            ValidIssuer = issuer,
            ValidAudience = audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey)),
            ClockSkew = TimeSpan.FromMinutes(1),
            // sub claim from JwtFactory holds the User.Id Guid.
            NameClaimType = JwtRegisteredClaimNames.Sub,
        };
    });

// Require authentication globally. Every endpoint is protected by default;
// public routes (OAuth callbacks, /health) opt out explicitly with .AllowAnonymous().
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

// JwtFactory issues JWTs after OAuth callback. OAuthHandler exchanges codes
// against Google and upserts the User row.
builder.Services.AddSingleton<JwtFactory>();
builder.Services.AddSingleton<PkceFlow>();
builder.Services.AddScoped<OAuthHandler>();

// Persist Data Protection keys to the application database. The key ring
// encrypts the PKCE state cookie (and any future protected payloads) and must
// survive API restarts and multi-instance deploys.
//   AppDbContext implements IDataProtectionKeyContext (DbSet<DataProtectionKey>).
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>()
    .SetApplicationName("FamilySplit");

// --- OpenAPI / Scalar -------------------------------------------------------------
// Only register the OpenAPI document generator in development — it adds a
// non-trivial chunk to startup time and is never used in production.
if (builder.Environment.IsDevelopment())
{
    builder.Services.AddOpenApi();
}

var app = builder.Build();

// --- Middleware pipeline ----------------------------------------------------------
// Security headers on every response — registered first so they are present even
// on error responses produced by middleware further down the pipeline.
app.UseMiddleware<SecurityHeadersMiddleware>();

// HSTS + HTTPS redirection are production-only: dev typically runs on a self-signed
// cert and `localhost` is exempt from HSTS preload anyway.
if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseResponseCompression();
app.UseSerilogRequestLogging();
app.UseMiddleware<ValidationExceptionMiddleware>();
app.UseCors("ClientApp");
app.UseAuthentication();
app.UseAuthorization();
// Enriches Serilog log entries with the authenticated caller's UserId and
// UserEmail (from JWT claims) for every subsequent log statement in the request.
app.UseMiddleware<UserLoggingContextMiddleware>();

// --- Health (anonymous) -----------------------------------------------------------
app.MapGet("/health", () => Results.Ok(new
{
    status = "ok",
    service = "FamilySplit.Api",
    utc = DateTimeOffset.UtcNow
})).AllowAnonymous();

// --- Endpoint groups --------------------------------------------------------------
app.MapAuthEndpoints();
app.MapUserEndpoints();
app.MapFamilyMemberEndpoints();   // GET /users/me/profile
app.MapAdminEndpoints();          // /admin/families — global-admin CRUD
app.MapFamilyEndpoints();         // /families/mine — own-family management
app.MapGroupEndpoints();          // /groups — CRUD + join + invite-code
app.MapGroupMemberEndpoints();    // no-op stub (members managed via Family endpoints)
app.MapActivityEndpoints();       // /groups/{groupId}/activities — CRUD + participants + close
app.MapExpenseEndpoints();        // /groups/{groupId}/activities/{activityId}/expenses — Phase 5
app.MapSettlementEndpoints();     // /groups/{groupId}/activities/{activityId}/settlements — Phase 6
app.MapDashboardEndpoints();      // /dashboard/stats — per-group statistics


// --- OpenAPI + Scalar UI (dev only) ----------------------------------------------
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi().AllowAnonymous();
    app.MapScalarApiReference().AllowAnonymous();
}

app.Run();

// Small helper used by future endpoints to pull the caller's UserId from the JWT.
public static class ClaimsPrincipalExtensions
{
    public static Guid GetUserId(this ClaimsPrincipal user)
    {
        var sub = user.FindFirstValue(ClaimTypes.NameIdentifier)
                  ?? user.FindFirstValue("sub")
                  ?? throw new UnauthorizedAccessException("JWT missing sub/NameIdentifier claim.");
        return Guid.Parse(sub);
    }
}
