using System.IO.Compression;
using System.Security.Claims;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.RateLimiting;
using FamilySplit.Api.Auth;
using FamilySplit.Api.Endpoints;
using FamilySplit.Api.Hubs;
using FamilySplit.Api.Middleware;
using FamilySplit.Application;
using FamilySplit.Application.Notifications;
using FamilySplit.Infrastructure;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.DataProtection.EntityFrameworkCore;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.IdentityModel.JsonWebTokens;
using Microsoft.IdentityModel.Tokens;
using Scalar.AspNetCore;
using Serilog;

var builder = WebApplication.CreateBuilder(args);

// Validate that all registered services can be constructed at startup, catching
// missing registrations and captive-dependency bugs before the first request.
// ValidateScopes catches scoped services accidentally consumed from singletons.
builder.Host.UseDefaultServiceProvider(options =>
{
    options.ValidateOnBuild = true;
    options.ValidateScopes = true;
});

// Remove the default "Server: Kestrel" response header to avoid advertising
// the server technology to potential attackers.
builder.WebHost.ConfigureKestrel(o => o.AddServerHeader = false);

// --- Logging -----------------------------------------------------------------------
// Serilog reads levels from appsettings. Console output format depends on the
// environment: structured JSON in production (parseable by Railway log drains /
// external log services) and human-readable text in development.
var isProduction = builder.Environment.IsProduction();
builder.Host.UseSerilog((ctx, lc) =>
{
    lc.ReadFrom.Configuration(ctx.Configuration)
      .Enrich.FromLogContext();

    if (isProduction)
        lc.WriteTo.Console(new Serilog.Formatting.Json.JsonFormatter());
    else
        lc.WriteTo.Console();
});

// Cache allowed origins once at startup — used by both CORS and the OAuth
// returnUrl allow-list (open-redirect guard in AuthEndpoints).
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
    ?? new[] { "https://localhost:5001", "http://localhost:5000" };

// --- CORS for Blazor WASM client --------------------------------------------------
builder.Services.AddCors(options =>
{
    options.AddPolicy("ClientApp", policy =>
    {
        policy.WithOrigins(allowedOrigins)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

// --- Response compression (gzip + brotli for JSON over HTTPS) --------------------
// Trims response payloads by ~70% for typical JSON responses, with a negligible
// CPU cost. EnableForHttps is safe here because the API only accepts JSON
// responses generated by our own code — no static files, no user-controlled
// content that could be vulnerable to BREACH-style attacks.
builder.Services.AddResponseCompression(o =>
{
    o.EnableForHttps = true;
    o.Providers.Add<BrotliCompressionProvider>();
    o.Providers.Add<GzipCompressionProvider>();
    o.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(new[] { "application/problem+json" });
});
builder.Services.Configure<BrotliCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);
builder.Services.Configure<GzipCompressionProviderOptions>(o => o.Level = CompressionLevel.Fastest);

// --- Rate limiting ----------------------------------------------------------------
// Two-tier protection:
//   • Global per-IP fixed window   — blanket safety net (300 req/min).
//   • Named "auth" sliding window  — tighter per-IP limit on auth endpoints
//     to slow brute-force and credential-stuffing (20 req/min, 15-s buckets).
//     20/min comfortably covers multi-tab silent refreshes while still being
//     far too low for any meaningful automated attack.
builder.Services.AddRateLimiter(options =>
{
    options.GlobalLimiter = PartitionedRateLimiter.Create<HttpContext, string>(ctx =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: ctx.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 300,
                Window = TimeSpan.FromMinutes(1),
                QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
                QueueLimit = 0,
            }));

    options.AddPolicy("auth", ctx =>
        RateLimitPartition.GetSlidingWindowLimiter(
            partitionKey: ctx.Connection.RemoteIpAddress?.ToString() ?? "unknown",
            factory: _ => new SlidingWindowRateLimiterOptions
            {
                PermitLimit = 20,
                Window = TimeSpan.FromMinutes(1),
                SegmentsPerWindow = 4,        // 15-second resolution
                QueueProcessingOrder = QueueProcessingOrder.OldestFirst,
                QueueLimit = 0,
            }));

    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;

    options.OnRejected = async (ctx, ct) =>
    {
        ctx.HttpContext.Response.StatusCode = StatusCodes.Status429TooManyRequests;
        ctx.HttpContext.Response.ContentType = "application/json";

        if (ctx.Lease.TryGetMetadata(MetadataName.RetryAfter, out var retryAfter))
        {
            ctx.HttpContext.Response.Headers.RetryAfter =
                ((int)retryAfter.TotalSeconds).ToString(System.Globalization.CultureInfo.InvariantCulture);
        }

        await ctx.HttpContext.Response.WriteAsync(
            """{"title":"Too many requests","status":429}""", ct);
    };
});

// --- HTTP client factory (needed by OAuthHandler for token exchange) -------------
// Timeout is delegated entirely to the resilience pipeline below, so we use
// InfiniteTimeSpan here — the TotalRequestTimeout handler acts as the backstop.
// Two retries handle transient Google 5xx/network blips without hammering the
// endpoint; exponential backoff with jitter avoids synchronized retry storms.
builder.Services.AddHttpClient("google-oauth", c =>
{
    c.Timeout = System.Threading.Timeout.InfiniteTimeSpan;
})
.AddStandardResilienceHandler(o =>
{
    o.Retry.MaxRetryAttempts = 2;
    o.Retry.UseJitter = true;
    o.Retry.Delay = TimeSpan.FromMilliseconds(300);
    o.AttemptTimeout.Timeout = TimeSpan.FromSeconds(12);
    o.TotalRequestTimeout.Timeout = TimeSpan.FromSeconds(35);
});

// --- Application + Infrastructure -------------------------------------------------
builder.Services.AddFamilySplitApplication();
builder.Services.AddFamilySplitInfrastructure(builder.Configuration, builder.Environment);

// --- Auth: JwtBearer + OAuth handler placeholders ---------------------------------
var jwt = builder.Configuration.GetSection("Jwt");
var signingKey = jwt["SigningKey"]
    ?? throw new InvalidOperationException("Missing config Jwt:SigningKey. Set via user-secrets or env.");
if (Encoding.UTF8.GetByteCount(signingKey) < 32)
    throw new InvalidOperationException("Jwt:SigningKey must be at least 32 bytes (256 bits) for HMAC-SHA256.");
var issuer = jwt["Issuer"] ?? "familysplit";
var audience = jwt["Audience"] ?? "familysplit-client";

builder.Services
    .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        // Use the modern JsonWebTokenHandler — faster than the legacy
        // JwtSecurityTokenHandler and the future-default for JwtBearer.
        options.MapInboundClaims = false;
        options.SaveToken = false;
        options.RequireHttpsMetadata = !builder.Environment.IsDevelopment();

        // SignalR: Blazor WASM cannot set Authorization headers on WebSocket
        // upgrade requests. The client passes the JWT as ?access_token= instead.
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"];
                if (!string.IsNullOrEmpty(accessToken) &&
                    context.HttpContext.Request.Path.StartsWithSegments("/hubs"))
                {
                    context.Token = accessToken;
                }
                return Task.CompletedTask;
            }
        };

        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            RequireExpirationTime = true,
            RequireSignedTokens = true,
            ValidIssuer = issuer,
            ValidAudience = audience,
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey)),
            ClockSkew = TimeSpan.FromMinutes(1),
            // sub claim from JwtFactory holds the User.Id Guid.
            NameClaimType = JwtRegisteredClaimNames.Sub,
        };
    });

// Serialize enums as strings so API responses are human-readable (e.g. "Open" not 0).
builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
});

// Require authentication globally. Every endpoint is protected by default;
// public routes (OAuth callbacks, /health) opt out explicitly with .AllowAnonymous().
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new Microsoft.AspNetCore.Authorization.AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

// --- SignalR -----------------------------------------------------------------------
// AddSignalR is part of the ASP.NET Core shared framework — no extra NuGet needed.
// SignalRNotificationService is scoped and registered as INotificationService so
// SettlementService can call it without a direct dependency on SignalR.
builder.Services.AddSignalR();
builder.Services.AddScoped<INotificationService, SignalRNotificationService>();

// JwtFactory issues JWTs after OAuth callback. OAuthHandler exchanges codes
// against Google and upserts the User row.
builder.Services.AddSingleton<JwtFactory>();
builder.Services.AddSingleton<PkceFlow>();
builder.Services.AddScoped<OAuthHandler>();

// Persist Data Protection keys to the application database. The key ring
// encrypts the PKCE state cookie (and any future protected payloads) and must
// survive API restarts and multi-instance deploys.
//   AppDbContext implements IDataProtectionKeyContext (DbSet<DataProtectionKey>).
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>()
    .SetApplicationName("FamilySplit");

// --- OpenAPI / Scalar -------------------------------------------------------------
// Only register the OpenAPI document generator in development — it adds a
// non-trivial chunk to startup time and is never used in production.
if (builder.Environment.IsDevelopment())
{
    builder.Services.AddOpenApi();
}

var app = builder.Build();

// --- Middleware pipeline ----------------------------------------------------------
// Forwarded headers MUST run first. Railway terminates TLS at its edge proxy and
// forwards the request to the container as plain HTTP with X-Forwarded-Proto: https.
// Until this middleware rewrites Request.Scheme and Request.Host, anything that
// reads them sees the raw http scheme — which causes UseHttpsRedirection to fire
// in a loop, builds http:// redirect_uris that Google rejects, and produces Secure
// cookies the browser won't store.
//
// KnownNetworks/KnownProxies are cleared because the proxy IPs Railway uses are
// not stable and we cannot enumerate them. The only safe alternative would be to
// hardcode Railway's egress range, which they don't publish.
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor
                     | ForwardedHeaders.XForwardedProto
                     | ForwardedHeaders.XForwardedHost
};
forwardedHeadersOptions.KnownIPNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);

// Security headers on every response — registered after ForwardedHeaders so any
// header values that depend on scheme (e.g. CSP report-uri) see the correct one.
app.UseMiddleware<SecurityHeadersMiddleware>();

// HSTS + HTTPS redirection are production-only: dev typically runs on a self-signed
// cert and `localhost` is exempt from HSTS preload anyway.
if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
    app.UseHttpsRedirection();
}

app.UseResponseCompression();
app.UseSerilogRequestLogging();
app.UseMiddleware<ValidationExceptionMiddleware>();
app.UseCors("ClientApp");
app.UseRateLimiter();

app.UseAuthentication();
app.UseAuthorization();
// Enriches Serilog log entries with the authenticated caller's UserId and
// UserEmail (from JWT claims) for every subsequent log statement in the request.
app.UseMiddleware<UserLoggingContextMiddleware>();

// --- Health (anonymous) -----------------------------------------------------------
app.MapGet("/health", () => Results.Ok(new
{
    status = "ok",
    service = "FamilySplit.Api",
    utc = DateTimeOffset.UtcNow
})).AllowAnonymous();

// --- Endpoint groups --------------------------------------------------------------
app.MapAuthEndpoints();
app.MapUserEndpoints();
app.MapFamilyMemberEndpoints();   // GET /users/me/profile
app.MapAdminEndpoints();          // /admin/families — global-admin CRUD
app.MapFamilyEndpoints();         // /families/mine — own-family management
app.MapGroupEndpoints();          // /groups — CRUD + join + invite-code
app.MapGroupMemberEndpoints();    // no-op stub (members managed via Family endpoints)
app.MapActivityEndpoints();       // /groups/{groupId}/activities — CRUD + participants + close
app.MapExpenseEndpoints();        // /groups/{groupId}/activities/{activityId}/expenses — Phase 5
app.MapSettlementEndpoints();     // /groups/{groupId}/activities/{activityId}/settlements — Phase 6
app.MapDashboardEndpoints();      // /dashboard/stats — per-group statistics
app.MapPushEndpoints();           // /push — VAPID subscription management

// SignalR hub — Blazor WASM passes JWT as ?access_token query param because
// WebSocket upgrade requests cannot carry Authorization headers.
app.MapHub<NotificationHub>("/hubs/notifications");


// --- OpenAPI + Scalar UI (dev only) ----------------------------------------------
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi().AllowAnonymous();
    app.MapScalarApiReference().AllowAnonymous();
}

app.Run();

// Exposed for WebApplicationFactory<Program> in integration tests.
public partial class Program { }

// Small helper used by future endpoints to pull the caller's UserId from the JWT.
public static class ClaimsPrincipalExtensions
{
    public static Guid GetUserId(this ClaimsPrincipal user)
    {
        var sub = user.FindFirstValue(ClaimTypes.NameIdentifier)
                  ?? user.FindFirstValue("sub")
                  ?? throw new UnauthorizedAccessException("JWT missing sub/NameIdentifier claim.");
        return Guid.Parse(sub);
    }
}
